### ISSUE TITLE
Better implementation of hang?

### ISSUE THREAD

**Issue by nixCodeX** [conal/checkers#41]
I may be mistaken but does `hang = hang` not serve as an adequate implementation, it does not seem to use much in the way of resources.

**Comment by conal** [comment]
I'd expect GHC's RTS to throw a "black hole" error.

**Comment by nixCodeX** [comment]
It didn’t when I tried it on ghci, optimisations may cause different behaviour though

**Comment by conal** [comment]
As I understand it, GHCi behaves differently from compiled Haskell code in this regard.

**Comment by nixCodeX** [comment]
You are indeed right
